/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.jogoempolgante;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author fluca
 */
public class bemEmpolgante extends javax.swing.JFrame {

    /**
     * Creates new form bemEmpolgante
     */
    public bemEmpolgante() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("Jogo Bem Empolgante");
        btn1.setText("");
        btn2.setText("A");
        btn3.setText("B");
        btn4.setText("C");
        btn5.setText("E");
        btn6.setText("F");
        btn7.setText("G");
        btn8.setText("D");
        btn9.setText("I");
        btn10.setText("J");
        btn11.setText("K");
        btn12.setText("H");
        btn13.setText("M");
        btn14.setText("N");
        btn15.setText("O");
        btn16.setText("L");
        
        
        ActionListener contaTempo = new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                tempoRestante--;
                lblTempo2.setText(String.valueOf(tempoRestante));
                if(tempoRestante == 0){
                    tempo.stop();
                    Object[] opcoes = {"Sim", "Não"};
                    int retorno = JOptionPane.showOptionDialog(null,
                            "Tempo esgotado! Deseja jogar novamente?",
                            "Tempo esgotado", JOptionPane.YES_NO_OPTION,
                            JOptionPane.QUESTION_MESSAGE, null,
                            opcoes, opcoes[0]);
                    if (retorno == 0){
                        recomecar();
                    } else {
                        dispose();
                    }
                }
            }
        };
        tempo = new Timer(1000,contaTempo);
        tempo.start();
    }

    private void recomecar() {
               lblTempo2.setText("300");
        tempoRestante = 300;
        btn1.setText("");
        btn2.setText("D");
        btn3.setText("O");
        btn4.setText("E");
        btn5.setText("I");
        btn6.setText("M");
        btn7.setText("J");
        btn8.setText("A");
        btn9.setText("G");
        btn10.setText("N");
        btn11.setText("B");
        btn12.setText("K");
        btn13.setText("H");
        btn14.setText("L");
        btn15.setText("F");
        btn16.setText("C");
        
        tempo.start();
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn10 = new javax.swing.JButton();
        btn11 = new javax.swing.JButton();
        btn12 = new javax.swing.JButton();
        btn13 = new javax.swing.JButton();
        btn14 = new javax.swing.JButton();
        btn15 = new javax.swing.JButton();
        btn16 = new javax.swing.JButton();
        lblTempo1 = new javax.swing.JLabel();
        lblTempo2 = new javax.swing.JLabel();
        btnRecomecar = new javax.swing.JButton();
        btnfechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10ActionPerformed(evt);
            }
        });

        btn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn11ActionPerformed(evt);
            }
        });

        btn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn12ActionPerformed(evt);
            }
        });

        btn13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn13ActionPerformed(evt);
            }
        });

        btn14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn14ActionPerformed(evt);
            }
        });

        btn15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn15ActionPerformed(evt);
            }
        });

        btn16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn16ActionPerformed(evt);
            }
        });

        lblTempo1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTempo1.setText("Tempo Restante");

        lblTempo2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTempo2.setForeground(new java.awt.Color(255, 0, 0));
        lblTempo2.setText("300");

        btnRecomecar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRecomecar.setText("Recomeçar");
        btnRecomecar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecomecarActionPerformed(evt);
            }
        });

        btnfechar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnfechar.setText("Fechar");
        btnfechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTempo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn14, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addComponent(lblTempo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRecomecar, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnfechar, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn8, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn12, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn16, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTempo1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTempo2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRecomecar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnfechar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnfecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfecharActionPerformed
        Object[] opcoes = {"Sim" ,"Não"};
        int retorno = JOptionPane.showOptionDialog(null,
                "Tem certeza que deseja fechar o jogo?",
                "Encerrar", JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, opcoes,
                opcoes[0]);
        if (retorno == 0){
            tempo.stop();
            dispose();
            
        }
    }//GEN-LAST:event_btnfecharActionPerformed

    private void btnRecomecarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecomecarActionPerformed
        recomecar();
    }//GEN-LAST:event_btnRecomecarActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        if(btn2.getText().equals("")){
           btn2.setText(btn1.getText());
           btn1.setText("");
           ganhou();
        } else if(btn5.getText().equals("")){
           btn5.setText(btn1.getText());
           btn1.setText("");
           ganhou();
        } 
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        if(btn1.getText().equals("")){
           btn1.setText(btn2.getText());
           btn2.setText("");
           ganhou();
        } else if(btn3.getText().equals("")){
           btn3.setText(btn2.getText());
           btn2.setText("");
           ganhou();
        } else if(btn6.getText().equals("")){
           btn6.setText(btn2.getText());
           btn2.setText("");
           ganhou();
        }
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        if(btn2.getText().equals("")){
           btn2.setText(btn3.getText());
           btn3.setText("");
           ganhou();
        }else if(btn4.getText().equals("")){
           btn4.setText(btn3.getText());
           btn3.setText("");
           ganhou();
        } else if(btn7.getText().equals("")){
           btn7.setText(btn3.getText());
           btn3.setText("");
           ganhou();
        }
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        if(btn3.getText().equals("")){
           btn3.setText(btn4.getText());
           btn4.setText("");
           ganhou();
        } if(btn8.getText().equals("")){
           btn8.setText(btn4.getText());
           btn4.setText("");
           ganhou();
        } 
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        if(btn1.getText().equals("")){
           btn1.setText(btn5.getText());
           btn5.setText("");
           ganhou();
        } else if(btn6.getText().equals("")){
           btn6.setText(btn5.getText());
           btn5.setText("");
           ganhou();
        } else if(btn9.getText().equals("")){
           btn9.setText(btn5.getText());
           btn5.setText("");
           ganhou();
        } 
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        if(btn2.getText().equals("")){
           btn2.setText(btn6.getText());
           btn6.setText("");
           ganhou();
        } else if(btn5.getText().equals("")){
           btn5.setText(btn6.getText());
           btn6.setText("");
           ganhou();
        } else if(btn7.getText().equals("")){
           btn7.setText(btn6.getText());
           btn6.setText("");
           ganhou();
        } else if(btn10.getText().equals("")){
           btn10.setText(btn6.getText());
           btn6.setText("");
           ganhou();
        } 
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        if(btn3.getText().equals("")){
           btn3.setText(btn7.getText());
           btn7.setText("");
           ganhou();
        } else if(btn6.getText().equals("")){
           btn6.setText(btn7.getText());
           btn7.setText("");
           ganhou();
        } else if(btn8.getText().equals("")){
           btn8.setText(btn7.getText());
           btn7.setText("");
           ganhou();
        } else if(btn11.getText().equals("")){
           btn11.setText(btn7.getText());
           btn7.setText("");
           ganhou();
        } 
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        if(btn4.getText().equals("")){
           btn4.setText(btn8.getText());
           btn8.setText("");
           ganhou();
        }  else if(btn7.getText().equals("")){
           btn7.setText(btn8.getText());
           btn8.setText("");
           ganhou();
        } else if(btn12.getText().equals("")){
           btn12.setText(btn8.getText());
           btn8.setText("");
           ganhou();
        } 
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
         if(btn5.getText().equals("")){
           btn5.setText(btn9.getText());
           btn9.setText("");
           ganhou();
        } else if(btn10.getText().equals("")){
           btn10.setText(btn9.getText());
           btn9.setText("");
           ganhou();
        } else if(btn13.getText().equals("")){
           btn13.setText(btn9.getText());
           btn9.setText("");
           ganhou();
        } 
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10ActionPerformed
        if(btn6.getText().equals("")){
           btn6.setText(btn10.getText());
           btn10.setText("");
           ganhou();
        } else if(btn9.getText().equals("")){
           btn9.setText(btn10.getText());
           btn10.setText("");
           ganhou();
        } else if(btn11.getText().equals("")){
           btn11.setText(btn10.getText());
           btn10.setText("");
           ganhou();
        } else if(btn14.getText().equals("")){
           btn14.setText(btn10.getText());
           btn10.setText("");
           ganhou();
        }
    }//GEN-LAST:event_btn10ActionPerformed

    private void btn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn11ActionPerformed
        if(btn7.getText().equals("")){
           btn7.setText(btn11.getText());
           btn11.setText("");
           ganhou();
        } else if(btn10.getText().equals("")){
           btn10.setText(btn11.getText());
           btn11.setText("");
           ganhou();
        } else if(btn12.getText().equals("")){
           btn12.setText(btn11.getText());
           btn11.setText("");
           ganhou();
        } else if(btn15.getText().equals("")){
           btn15.setText(btn11.getText());
           btn11.setText("");
           ganhou();
        }
    }//GEN-LAST:event_btn11ActionPerformed

    private void btn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn12ActionPerformed
        if(btn8.getText().equals("")){
           btn8.setText(btn12.getText());
           btn12.setText("");
           ganhou();
        } else  if(btn11.getText().equals("")){
           btn11.setText(btn12.getText());
           btn12.setText("");
           ganhou();
        } else  if(btn16.getText().equals("")){
           btn16.setText(btn12.getText());
           btn12.setText("");
           ganhou();
        }
    }//GEN-LAST:event_btn12ActionPerformed

    private void btn13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn13ActionPerformed
         if(btn9.getText().equals("")){
           btn9.setText(btn13.getText());
           btn13.setText("");
           ganhou();
        } else if(btn14.getText().equals("")){
           btn14.setText(btn13.getText());
           btn13.setText("");
           ganhou();
        }
    }//GEN-LAST:event_btn13ActionPerformed

    private void btn14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn14ActionPerformed
         if(btn10.getText().equals("")){
           btn10.setText(btn14.getText());
           btn14.setText("");
           ganhou();
        } else if(btn13.getText().equals("")){
           btn13.setText(btn14.getText());
           btn14.setText("");
           ganhou();
        } else if(btn15.getText().equals("")){
           btn15.setText(btn14.getText());
           btn14.setText("");
           ganhou();
        }
    }//GEN-LAST:event_btn14ActionPerformed

    private void btn15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn15ActionPerformed
        if(btn11.getText().equals("")){
           btn11.setText(btn15.getText());
           btn15.setText("");
           ganhou();
        } else if(btn14.getText().equals("")){
           btn14.setText(btn15.getText());
           btn15.setText("");
           ganhou();
        } else if(btn16.getText().equals("")){
           btn16.setText(btn15.getText());
           btn15.setText("");
           ganhou();
        }
    }//GEN-LAST:event_btn15ActionPerformed

    private void btn16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn16ActionPerformed
        if(btn12.getText().equals("")){
           btn12.setText(btn16.getText());
           btn16.setText("");
           ganhou();
        } else if(btn15.getText().equals("")){
           btn15.setText(btn16.getText());
           btn16.setText("");
           ganhou();
        }
    }//GEN-LAST:event_btn16ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bemEmpolgante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bemEmpolgante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bemEmpolgante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bemEmpolgante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bemEmpolgante().setVisible(true);
            }
        });
    }
    
    private void  ganhou(){
        if (btn1.getText().equals("A") && 
            btn2.getText().equals("B") && 
            btn3.getText().equals("C") && 
            btn4.getText().equals("D") &&
            btn5.getText().equals("E") && 
            btn6.getText().equals("F") &&
            btn7.getText().equals("G") && 
            btn8.getText().equals("H") &&
            btn9.getText().equals("I")&& 
            btn10.getText().equals("J") &&
            btn11.getText().equals("K") && 
            btn12.getText().equals("L") &&
            btn13.getText().equals("M") && 
            btn14.getText().equals("N") &&
            btn15.getText().equals("O") && 
            btn16.getText().equals("")) {
                tempo.stop();
                Object[] opcoes = {"Sim" ,"Não"};
                int retorno = JOptionPane.showOptionDialog(null,
                "Parabéns! Deseja jogar novamente?",
                "Parabéns", JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, opcoes,
                opcoes[0]);
                if (retorno == 0){
                    recomecar();
                }else{
                    dispose();
                }
        }
    }
    
    private int tempoRestante = 300;
    private Timer tempo;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn10;
    private javax.swing.JButton btn11;
    private javax.swing.JButton btn12;
    private javax.swing.JButton btn13;
    private javax.swing.JButton btn14;
    private javax.swing.JButton btn15;
    private javax.swing.JButton btn16;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnRecomecar;
    private javax.swing.JButton btnfechar;
    private javax.swing.JLabel lblTempo1;
    private javax.swing.JLabel lblTempo2;
    // End of variables declaration//GEN-END:variables
}
