package pkApresentacao;

import javax.swing.JOptionPane;
import pkBanco.ContatoDAO;
import pkNegocio.Contato;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author fluca
 */
public class CadastrarContato extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastrarContato
     */
    public CadastrarContato() {
        super("Cadastrar Contato", false, true,
                false, false);
        //titulo, redimensionar, fechar, maximizar, minimizar
        this.setLocation(450, 150);
        initComponents();
        getRootPane().setDefaultButton(btnCadastrar);
        
    }
    
    public CadastrarContato(String nome, String telefone) {
        super("Alterar Contato", false, true,
                false, false);
        //titulo, redimensionar, fechar, maximizar, minimizar
        this.setLocation(450, 150);
        initComponents();
        getRootPane().setDefaultButton(btnCadastrar);
        btnCadastrar.setText("Alterar");
        menuCadastrar.setText("Alterar");
        txtNome.setText(nome);
        txtTelefone.setText(telefone);
        nomeAtual = nome;
        telefoneAtual = telefone;
    }
    
    private void cadastrarAlterar() {
        if(txtNome.getText().equals("")){
            JOptionPane.showMessageDialog(null,
                    "Digite o nome!!!", "Nome",
                    JOptionPane.ERROR_MESSAGE);
            txtNome.requestFocus();
        } else  if(txtTelefone.getText().equals("")){
            JOptionPane.showMessageDialog(null,
                    "Digite o telefone!!", "Nome",
                    JOptionPane.ERROR_MESSAGE);
            txtTelefone.requestFocus();
        } else if (btnCadastrar.getText().equals("Cadastrar")){
            ContatoDAO contatoDAO = new ContatoDAO();
            Contato contato = new Contato (txtNome.getText().toUpperCase(), 
            txtTelefone.getText().toUpperCase());
            contatoDAO.cadastrarContato(contato);
            JOptionPane.showMessageDialog(null,
                    "Contato cadastrado com sucesso!",
                    "Cadastrado", JOptionPane.INFORMATION_MESSAGE);
            dispose();
        } else if (btnCadastrar.getText().equals("Alterar")){
            Object[] opcoes = {"Sim", "Não"};
            int retorno = JOptionPane.showOptionDialog(null,
                    "Tem certeza que deseja alterar?",
                    "Alterar", JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE,null,
                    opcoes,opcoes[0]);
            if (retorno == 0){
                ContatoDAO contatoDAO = new ContatoDAO();
                Contato contato = new Contato
                (txtNome.getText().toUpperCase(),
                 txtTelefone.getText().toUpperCase());
                Contato contatoAtual = new Contato
                (nomeAtual, telefoneAtual);
                 contatoDAO.atualizarContato(contato, contatoAtual);
                 JOptionPane.showMessageDialog(null,
                         "Contato alterado com sucesso!",
                         "Alterado", JOptionPane.INFORMATION_MESSAGE);
                 dispose();
            }
        }
    }    
    
    private void fechar(){
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblTelefone = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        itemCadastrar = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        menuCadastrar = new javax.swing.JMenuItem();
        itemFechar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();

        lblNome.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblNome.setText("Nome");

        txtNome.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        lblTelefone.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTelefone.setText("Telefone");

        txtTelefone.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        btnCadastrar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnFechar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        menuArquivo.setText("Arquivo");

        menuCadastrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuCadastrar.setText("Cadastrar");
        menuCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastrarActionPerformed(evt);
            }
        });
        menuArquivo.add(menuCadastrar);

        itemFechar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itemFechar.setText("Fechar");
        itemFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemFecharActionPerformed(evt);
            }
        });
        menuArquivo.add(itemFechar);
        menuArquivo.add(jSeparator1);

        itemCadastrar.add(menuArquivo);

        setJMenuBar(itemCadastrar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTelefone)
                    .addComponent(lblNome))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTelefone))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar)
                    .addComponent(btnFechar))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        cadastrarAlterar();
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void itemFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemFecharActionPerformed
        fechar();
    }//GEN-LAST:event_itemFecharActionPerformed

    private void menuCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrarActionPerformed
        cadastrarAlterar();
    }//GEN-LAST:event_menuCadastrarActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        fechar();
    }//GEN-LAST:event_btnFecharActionPerformed

    private String nomeAtual,telefoneAtual;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnFechar;
    private javax.swing.JMenuBar itemCadastrar;
    private javax.swing.JMenuItem itemFechar;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JMenuItem menuCadastrar;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
